spring.application.name=backend

spring.datasource.url=jdbc:postgresql://localhost:5432/civicsnap
spring.datasource.username=postgres
spring.datasource.password=@Kl13b055

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

spring.flyway.enabled=true